<Project Sdk="Microsoft.NET.Sdk.Web">
   <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <UserSecretsId>655dfd6e-9c6e-4d33-bb1c-ab868998e338</UserSecretsId>
      <SpaRoot>ClientApp/</SpaRoot>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
   </PropertyGroup>

   <ItemGroup>
      <PackageReference Include="FluentNHibernate" Version="3.4.1" />
      <PackageReference Include="KitchenPC.Core" Version="2.0.0" />
      <PackageReference Include="KitchenPC.Core.AspNetCore" Version="2.0.0" />
      <PackageReference Include="KitchenPC.DB" Version="2.0.0" />
      <PackageReference Include="NHibernate" Version="5.7.0" />
      <PackageReference Include="Npgsql" Version="10.0.3" />
   </ItemGroup>

   <ItemGroup>
      <Content Remove="$(SpaRoot)**" />
      <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules/**" />
   </ItemGroup>

   <Target Name="BuildClient" BeforeTargets="ComputeFilesToPublish">
      <Exec WorkingDirectory="$(SpaRoot)" Command="npm ci" />
      <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />
      <ItemGroup>
         <ClientDist Include="wwwroot/**" />
         <ResolvedFileToPublish Include="@(ClientDist->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
            <RelativePath>wwwroot/%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
         </ResolvedFileToPublish>
      </ItemGroup>
   </Target>
</Project>
